# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-02 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('amount', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('universal_product_code', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'universal_product_code')]),
        ),
    ]
